dist: xenial

language: node_js
node_js: '12'

script:
  - rm -rf node_modules && npm i
  - npm run test
  - npm run build -- --report

before_deploy: scripts/before-deploy.sh

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: dist
    repo: $DEPLOY_REPO
    target_branch: $DEPLOY_TARGET_BRANCH
    name: $DEPLOY_NAME
    email: $DEPLOY_EMAIL
    on:
      all_branches: true
      condition: $DEPLOY_REPO
  - provider: script
    skip_cleanup: true
    script: scripts/deploy-stage.sh
    on:
      all_branches: true
